apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-http
spec:
  containers:
    - name: nginx
      image: k8s.gcr.io/nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 9090
        initialDelaySeconds: 3
        periodSeconds: 3
