apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mongodb-dev
  labels:
    app: mongodb-dev
spec:
  clusterIP: None
  selector:
    app: mongodb-dev
  ports:
    - port: 27017
      targetPort: 27017
