apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-longhorm-test
  namespace: dev
spec:
  #storageClassName: longhorn
  volumeMode: Filesystem
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeAttributes:
      numberOfReplicates: '2'
      staleReplicaTimeout: '20'
    volumeHandle: pv-longhorm-test
