apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim
  namespace: dev
spec:
  #storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

