apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: pv-storage-test
          mountPath: /usr/share/nginx/html

  volumes:
    - name: pv-storage-test
      persistentVolumeClaim:
        claimName: local-pvc-claim