apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name:  empty-dir-pod
spec:
  containers:
    - name: alpine-vl-empty-dir
      image: alpine
      args:
        - sleep
        - "120"
      volumeMounts:
        - mountPath: /data
          name: empty-dir-vl
  volumes:
    - name: empty-dir-vl
      emptyDir: {}
