apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-chef-hpa-ram
  namespace: dev
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 20
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-dep-chef